package com.zyhn.mapper;

import com.zyhn.entity.WaybillStatus;
import org.apache.ibatis.annotations.*;

import java.util.Date;

/**
 * @author chaoyue
 */
@Mapper
public interface WaybillStatusMapper {

	@Insert({"insert into TRANS_ORDER( TRANS_NO,VEHICLE_NO,CARRIER_CODE,CARRIER_NAME,TRANS_MODE,ORDER_STATE,SEND_ADDRESS,RECV_ADDRESS,SHIPPING_ADDRESS,MATERIAL_TYPE_BIG,MATERIAL_TYPE_BIG_NAME,MATERIAL_TYPE_SMALL,MATERIAL_TYPE_SMALL_NAME,MATERIAL_CODE,MATERIAL_NAME,MATERIAL_SPEC,MATERIAL_PACK,MATERIAL_ITEM,HCS_GRADE_CODE,HCS_GRADE_NAME,LOAD_QTY,PACK_UNIT,MANU_ENT_CODE,MANU_ENT_NAME,OWNER_ID,CONTACT_NUMBER,SOURCE_ID,SALE_DEALER_NAME,RECV_DEALER_NAME,EXPECTED_SEND_TIME,SEND_TIME,EXPECTED_RECV_TIME,RECV_TIME,ORDER_ID,ORDER_NO,SOURCE_SYS,CREATE_USER,CREATE_TIME,UPDATE_TIME,DELETE_STATE,STANDARD_MANU_ENT_CODE,STANDARD_MANU_ENT_NAME,OWNER_SECTOR_CODE,OWNER_NAME,TRANSFER_TYPE,ID_NUMBER) values (#{TRANS_NO},#{VEHICLE_NO},#{CARRIER_CODE},#{CARRIER_NAME},#{TRANS_MODE},#{ORDER_STATE},#{SEND_ADDRESS},#{RECV_ADDRESS},#{SHIPPING_ADDRESS},#{MATERIAL_TYPE_BIG},#{MATERIAL_TYPE_BIG_NAME},#{MATERIAL_TYPE_SMALL},#{MATERIAL_TYPE_SMALL_NAME},#{MATERIAL_CODE},#{MATERIAL_NAME},#{MATERIAL_SPEC},#{MATERIAL_PACK},#{MATERIAL_ITEM},#{HCS_GRADE_CODE},#{HCS_GRADE_NAME},#{LOAD_QTY},#{PACK_UNIT},#{MANU_ENT_CODE},#{MANU_ENT_NAME},#{OWNER_ID},#{CONTACT_NUMBER},#{SOURCE_ID},#{SALE_DEALER_NAME},#{RECV_DEALER_NAME},#{EXPECTED_SEND_TIME},#{SEND_TIME},#{EXPECTED_RECV_TIME},#{RECV_TIME},#{ORDER_ID},#{ORDER_NO},#{SOURCE_SYS},#{CREATE_USER},#{CREATE_TIME},#{UPDATE_TIME},#{DELETE_STATE},#{STANDARD_MANU_ENT_CODE},#{STANDARD_MANU_ENT_NAME},#{OWNER_SECTOR_CODE},#{OWNER_NAME},#{TRANSFER_TYPE},#{ID_NUMBER} )"})
	int insertOrUpdate(WaybillStatus waybill);

	@Update({"UPDATE TRANS_ORDER SET ORDER_STATE=#{status} ,UPDATE_TIME=#{updateTime} WHERE TRANS_NO=#{code}"})
	int update(@Param("status") String status, @Param("code")String code, @Param("updateTime") Date updateTime);

}